if _G.IY_DEBUG ~= true and IY_LOADED then
    -- error("NavineX is already running!",0)
    return
end

pcall(function() getgenv().IY_LOADED = true end)

COREGUI = game:GetService("CoreGui")
if not game:IsLoaded() then
    local notLoaded = Instance.new("Message")
    notLoaded.Parent = COREGUI
    notLoaded.Text = 'NavineX is waiting for the game to load'
    game.Loaded:Wait()
    notLoaded:Destroy()
end

currentVersion = '5.9.3'

Players = game:GetService("Players")

Holder = Instance.new("Frame")
Title = Instance.new("TextLabel")
Dark = Instance.new("Frame")
Cmdbar = Instance.new("TextBox")
CMDsF = Instance.new("ScrollingFrame")
cmdListLayout = Instance.new("UIListLayout")
SettingsButton = Instance.new("ImageButton")
ColorsButton = Instance.new("ImageButton")
Settings = Instance.new("Frame")
Prefix = Instance.new("TextLabel")
PrefixBox = Instance.new("TextBox")
Keybinds = Instance.new("TextLabel")
StayOpen = Instance.new("TextLabel")
Button = Instance.new("Frame")
On = Instance.new("TextButton")
Positions = Instance.new("TextLabel")
EventBind = Instance.new("TextLabel")
Plugins = Instance.new("TextLabel")
Example = Instance.new("TextButton")
Notification = Instance.new("Frame")
Title_2 = Instance.new("TextLabel")
Text_2 = Instance.new("TextLabel")
CloseButton = Instance.new("TextButton")
CloseImage = Instance.new("ImageLabel")
PinButton = Instance.new("TextButton")
PinImage = Instance.new("ImageLabel")
Tooltip = Instance.new("Frame")
Title_3 = Instance.new("TextLabel")
Description = Instance.new("TextLabel")
IntroBackground = Instance.new("Frame")
Logo = Instance.new("ImageLabel")
Credits = Instance.new("TextBox")
KeybindsFrame = Instance.new("Frame")
Close = Instance.new("TextButton")
Add = Instance.new("TextButton")
Delete = Instance.new("TextButton")
Holder_2 = Instance.new("ScrollingFrame")
Example_2 = Instance.new("Frame")
Text_3 = Instance.new("TextLabel")
Delete_2 = Instance.new("TextButton")
KeybindEditor = Instance.new("Frame")
background_2 = Instance.new("Frame")
Dark_3 = Instance.new("Frame")
Directions = Instance.new("TextLabel")
BindTo = Instance.new("TextButton")
TriggerLabel = Instance.new("TextLabel")
BindTriggerSelect = Instance.new("TextButton")
Add_2 = Instance.new("TextButton")
Toggles = Instance.new("ScrollingFrame")
ClickTP  = Instance.new("TextLabel")
Select = Instance.new("TextButton")
ClickDelete = Instance.new("TextLabel")
Select_2 = Instance.new("TextButton")
Cmdbar_2 = Instance.new("TextBox")
Cmdbar_3 = Instance.new("TextBox")
CreateToggle = Instance.new("TextLabel")
Button_2 = Instance.new("Frame")
On_2 = Instance.new("TextButton")
shadow_2 = Instance.new("Frame")
PopupText_2 = Instance.new("TextLabel")
Exit_2 = Instance.new("TextButton")
ExitImage_2 = Instance.new("ImageLabel")
PositionsFrame = Instance.new("Frame")
Close_3 = Instance.new("TextButton")
Delete_5 = Instance.new("TextButton")
Part = Instance.new("TextButton")
Holder_4 = Instance.new("ScrollingFrame")
Example_4 = Instance.new("Frame")
Text_5 = Instance.new("TextLabel")
Delete_6 = Instance.new("TextButton")
TP = Instance.new("TextButton")
AliasesFrame = Instance.new("Frame")
Close_2 = Instance.new("TextButton")
Delete_3 = Instance.new("TextButton")
Holder_3 = Instance.new("ScrollingFrame")
Example_3 = Instance.new("Frame")
Text_4 = Instance.new("TextLabel")
Delete_4 = Instance.new("TextButton")
Aliases = Instance.new("TextLabel")
PluginsFrame = Instance.new("Frame")
Close_4 = Instance.new("TextButton")
Add_3 = Instance.new("TextButton")
Holder_5 = Instance.new("ScrollingFrame")
Example_5 = Instance.new("Frame")
Text_6 = Instance.new("TextLabel")
Delete_7 = Instance.new("TextButton")
PluginEditor = Instance.new("Frame")
background_3 = Instance.new("Frame")
Dark_2 = Instance.new("Frame")
Img = Instance.new("ImageButton")
AddPlugin = Instance.new("TextButton")
FileName = Instance.new("TextBox")
About = Instance.new("TextLabel")
Directions_2 = Instance.new("TextLabel")
shadow_3 = Instance.new("Frame")
PopupText_3 = Instance.new("TextLabel")
Exit_3 = Instance.new("TextButton")
ExitImage_3 = Instance.new("ImageLabel")
AliasHint = Instance.new("TextLabel")
PluginsHint = Instance.new("TextLabel")
PositionsHint = Instance.new("TextLabel")
ToPartFrame = Instance.new("Frame")
background_4 = Instance.new("Frame")
ChoosePart = Instance.new("TextButton")
CopyPath = Instance.new("TextButton")
Directions_3 = Instance.new("TextLabel")
Path = Instance.new("TextLabel")
shadow_4 = Instance.new("Frame")
PopupText_5 = Instance.new("TextLabel")
Exit_4 = Instance.new("TextButton")
ExitImage_5 = Instance.new("ImageLabel")
logs = Instance.new("Frame")
shadow = Instance.new("Frame")
Hide = Instance.new("TextButton")
ImageLabel = Instance.new("ImageLabel")
PopupText = Instance.new("TextLabel")
Exit = Instance.new("TextButton")
ImageLabel_2 = Instance.new("ImageLabel")
background = Instance.new("Frame")
chat = Instance.new("Frame")
Clear = Instance.new("TextButton")
SaveChatlogs = Instance.new("TextButton")
Toggle = Instance.new("TextButton")
scroll_2 = Instance.new("ScrollingFrame")
join = Instance.new("Frame")
Toggle_2 = Instance.new("TextButton")
Clear_2 = Instance.new("TextButton")
scroll_3 = Instance.new("ScrollingFrame")
listlayout = Instance.new("UIListLayout",scroll_3)
selectChat = Instance.new("TextButton")
selectJoin = Instance.new("TextButton")

-- Define color variables for theme
local shade1Color = Color3.fromRGB(0, 0, 0) -- Black
local shade2Color = Color3.fromRGB(65, 105, 225) -- Royal Blue
local shade3Color = Color3.fromRGB(78, 78, 79) -- Dark Gray
local text1Color = Color3.new(1, 1, 1) -- White
local text2Color = Color3.new(0, 0, 0) -- Black
local scrollColor = Color3.fromRGB(78,78,79)

-- Replace color assignments in code
local function setColor(instance, color)
    if instance then
        instance.BackgroundColor3 = color
    end
end

-- Example: setting title text
Title.Text = "NavineX FE v" .. currentVersion

-- Now, set colors for key UI elements
setColor(Holder, shade1Color)
setColor(Dark, shade3Color)
setColor(Cmdbar, shade1Color)
setColor(CMDsF, shade3Color)
setColor(Settings, shade1Color)
setColor(Prefix, text1Color)
setColor(PrefixBox, shade1Color)
setColor(Keybinds, text1Color)
setColor(StayOpen, text1Color)
setColor(Button, shade1Color)
setColor(On, shade2Color)
setColor(Positions, text1Color)
setColor(EventBind, text1Color)
setColor(Plugins, text1Color)
setColor(Example, shade2Color)
setColor(Notification, shade3Color)
setColor(Title_2, text1Color)
setColor(Text_2, text1Color)
setColor(CloseButton, shade2Color)
setColor(PinButton, shade2Color)
setColor(Tooltip, shade3Color)
setColor(Title_3, text1Color)
setColor(Description, text1Color)
setColor(IntroBackground, shade1Color)
setColor(Logo, shade2Color)
setColor(Credits, text1Color)
setColor(KeybindsFrame, shade1Color)
setColor(Close, shade2Color)
setColor(Add, shade2Color)
setColor(Delete, shade2Color)
setColor(Holder_2, shade3Color)
setColor(Example_2, shade2Color)
setColor(Text_3, text1Color)
setColor(Delete_2, shade2Color)
setColor(KeybindEditor, shade1Color)
setColor(background_2, shade1Color)
setColor(Dark_3, shade3Color)
setColor(Directions, text1Color)
setColor(BindTo, shade2Color)
setColor(TriggerLabel, text1Color)
setColor(BindTriggerSelect, shade2Color)
setColor(Add_2, shade2Color)
setColor(Toggles, shade3Color)
setColor(ClickTP, text1Color)
setColor(Select, shade2Color)
setColor(ClickDelete, text1Color)
setColor(Select_2, shade2Color)
setColor(Cmdbar_2, shade1Color)
setColor(Cmdbar_3, shade1Color)
setColor(CreateToggle, text1Color)
setColor(Button_2, shade1Color)
setColor(On_2, shade2Color)
setColor(shadow_2, shade3Color)
setColor(PopupText_2, text1Color)
setColor(Exit_2, shade2Color)
setColor(ExitImage_2, shade2Color)
setColor(PositionsFrame, shade1Color)
setColor(Close_3, shade2Color)
setColor(Delete_5, shade2Color)
setColor(Part, shade2Color)
setColor(Holder_4, shade3Color)
setColor(Example_4, shade2Color)
setColor(Text_5, text1Color)
setColor(Delete_6, shade2Color)
setColor(TP, shade2Color)
setColor(AliasesFrame, shade1Color)
setColor(Close_2, shade2Color)
setColor(Delete_3, shade2Color)
setColor(Holder_3, shade3Color)
setColor(Example_3, shade2Color)
setColor(Text_4, text1Color)
setColor(Delete_4, shade2Color)
setColor(Aliases, text1Color)
setColor(PluginsFrame, shade1Color)
setColor(Close_4, shade2Color)
setColor(Add_3, shade2Color)
setColor(Holder_5, shade3Color)
setColor(Example_5, shade2Color)
setColor(Text_6, text1Color)
setColor(Delete_7, shade2Color)
setColor(PluginEditor, shade1Color)
setColor(background_3, shade1Color)
setColor(Dark_2, shade3Color)
setColor(Img, shade2Color)
setColor(AddPlugin, shade2Color)
setColor(About, text1Color)
setColor(Directions_2, text1Color)
setColor(shadow_3, shade3Color)
setColor(PopupText_3, text1Color)
setColor(Exit_3, shade2Color)
setColor(ExitImage_3, shade2Color)
setColor(AliasHint, text1Color)
setColor(PluginsHint, text1Color)
setColor(PositionsHint, text1Color)
setColor(ToPartFrame, shade1Color)
setColor(background_4, shade1Color)
setColor(ChoosePart, shade2Color)
setColor(CopyPath, shade2Color)
setColor(Directions_3, text1Color)
setColor(Path, text1Color)
setColor(shadow_4, shade3Color)
setColor(PopupText_5, text1Color)
setColor(Exit_4, shade2Color)
setColor(ExitImage_5, shade2Color)
setColor(logs, shade1Color)
setColor(shadow, shade3Color)
setColor(Hide, shade2Color)
setColor(ImageLabel, shade2Color)
setColor(PopupText, text1Color)
setColor(Exit, shade2Color)
setColor(ImageLabel_2, shade2Color)
setColor(background, shade1Color)
setColor(chat, shade1Color)
setColor(Clear, shade2Color)
setColor(SaveChatlogs, shade2Color)
setColor(Toggle, shade2Color)
setColor(scroll_2, shade3Color)
setColor(join, shade1Color)
setColor(Toggle_2, shade2Color)
setColor(Clear_2, shade2Color)
setColor(scroll_3, shade3Color)
setColor(selectChat, shade2Color)
setColor(selectJoin, shade2Color)

-- Replace all "Infinite Yield" references in text labels
Title.Text = "NavineX FE v" .. currentVersion

-- Replace all file references from ".iy" to ".navxx" in loading/saving functions
-- Example:
-- readfile("NavineX_FE.navxx")
-- writefile("NavineX_FE.navxx", data)

-- The above code snippets demonstrate how to adapt your code for these changes.
-- Make sure to replace all relevant instances accordingly throughout your full script.
